spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapp
    driver-clas-name: org.mysql.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect